
Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations:
append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [1]:
list=[64,98,49,30,76]
list

[64, 98, 49, 30, 76]

In [2]:
list.append(85)
list

[64, 98, 49, 30, 76, 85]

In [3]:
list.extend([56,13,42])
list

[64, 98, 49, 30, 76, 85, 56, 13, 42]

In [4]:
list.insert(0,10)
list

[10, 64, 98, 49, 30, 76, 85, 56, 13, 42]

In [5]:
list.remove(30)
list

[10, 64, 98, 49, 76, 85, 56, 13, 42]

In [6]:
list.pop(6)
list

[10, 64, 98, 49, 76, 85, 13, 42]

In [7]:
list.index(64)
list

[10, 64, 98, 49, 76, 85, 13, 42]

In [8]:
list.count(2)
list

[10, 64, 98, 49, 76, 85, 13, 42]

In [9]:
list.sort()
list

[10, 13, 42, 49, 64, 76, 85, 98]

In [10]:
list.reverse()
list

[98, 85, 76, 64, 49, 42, 13, 10]

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [11]:
tuple=("Komal","Karan","Kshitija")
tuple

('Komal', 'Karan', 'Kshitija')

In [12]:
tuple[1]="Sakshi"

TypeError: 'tuple' object does not support item assignment

==> Tuples are immutable - once a tuple is created, its elements cannot be changed, added, or removed.
Python gives an error because it does not allow changing items in a tuple.
If you want to change values, you should use a list instead of a tuple.

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [13]:
Set={54,37,82,20,89,92,82}
Set

{20, 37, 54, 82, 89, 92}

Sets do not allow duplicates ==> The number (82) shows only once , Even we write it twice

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [14]:
Dic={"Name":"Komal","Age":20,"City":"Pune"}
print("Original Dictonary : ",Dic)

Original Dictonary :  {'Name': 'Komal', 'Age': 20, 'City': 'Pune'}

In [15]:
Dic["Age"]=21
Dic["Email"]="komalgulve2gmail.com"
print("Updated Dictonary : ",Dic)

Updated Dictonary :  {'Name': 'Komal', 'Age': 21, 'City': 'Pune', 'Email': 'komalgulve2gmail.com'}

Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [18]:
age=int(input("Enter your age"));
if(age>18):
    print("person is eligible to vote")
else:
    print("person is not eligible to vote")

Enter your age 20

person is eligible to vote

6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [19]:
marks=40

if (marks >= 90):
    print("A")
elif (marks >= 75):
    print("B")
elif (marks >= 50):
   print("C")
else:
    print("Fail")

Fail

7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [20]:
num=int(input("Enter a number : "))

if num>0:
    if num%2==0:
        print(f"{num} is positive and even .")
    else:
        print(f"{num} is positive but odd ")
elif num==0:
    print("The number is Zero ")
else:
    print(f"{num} is negative")

Enter a number :  5

5 is positive but odd

Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [21]:
import numpy as np

In [22]:
array_1d=np.array([1,2,3,4,5])
print(array_1d)

[1 2 3 4 5]

In [24]:
arr=np.arange(10,70,10)
print(arr)

[10 20 30 40 50 60]

In [25]:
array_2d=arr.reshape(2,3)
print(array_2d)

[[10 20 30]
 [40 50 60]]

In [26]:
arr_2d=np.array([[10,20,30],[40,50,60]])
print (arr_2d)

[[10 20 30]
 [40 50 60]]

In [27]:
arrays_2d=array_2d.reshape(3,2)
print(arrays_2d)

[[10 20]
 [30 40]
 [50 60]]

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [28]:
ran=np.random.randint(0,101,size=(4,4))
print(ran)

[[ 78  24  22  37]
 [ 70   0 100  84]
 [ 55  11  21  47]
 [ 49  29  70  92]]

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [29]:
array_2d=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(array_2d)

[[10 20 30]
 [40 50 60]
 [70 80 90]]

In [30]:
import pandas as pd

In [32]:
df=pd.DataFrame(array_2d)
df

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [33]:
df.columns=("A","B","C")
df

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [34]:

data={
    'Name':["Komal","Yash","Maya","Megha","Pooja","Roshan","Tejas","Swaraj","Sakshi","Madhu"],
    'Age':[21,20,22,23,26,28,30,53,62,70],
    'City':["Pu","Mu","Na","Ja","Pu","Na","Th","Sa","Be","Pa"],
    'Salary':[900000,20000,3000,87350,np.nan,30600,10000,19000,np.nan,72000]}
df=pd.DataFrame(data)
df

     Name  Age City    Salary
0   Komal   21   Pu  900000.0
1    Yash   20   Mu   20000.0
2    Maya   22   Na    3000.0
3   Megha   23   Ja   87350.0
4   Pooja   26   Pu       NaN
5  Roshan   28   Na   30600.0
6   Tejas   30   Th   10000.0
7  Swaraj   53   Sa   19000.0
8  Sakshi   62   Be       NaN
9   Madhu   70   Pa   72000.0

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes

In [36]:
df.describe()

             Age         Salary
count  10.000000       8.000000
mean   35.500000  142743.750000
std    18.751296  307435.047074
min    20.000000    3000.000000
25%    22.250000   16750.000000
50%    27.000000   25300.000000
75%    47.250000   75837.500000
max    70.000000  900000.000000

In [37]:
name_city=df[['Name','City']]
print(name_city)

     Name City
0   Komal   Pu
1    Yash   Mu
2    Maya   Na
3   Megha   Ja
4   Pooja   Pu
5  Roshan   Na
6   Tejas   Th
7  Swaraj   Sa
8  Sakshi   Be
9   Madhu   Pa

In [38]:
df_drop=df.drop(columns=['City'])
df_drop

     Name  Age    Salary
0   Komal   21  900000.0
1    Yash   20   20000.0
2    Maya   22    3000.0
3   Megha   23   87350.0
4   Pooja   26       NaN
5  Roshan   28   30600.0
6   Tejas   30   10000.0
7  Swaraj   53   19000.0
8  Sakshi   62       NaN
9   Madhu   70   72000.0

In [39]:
salary_mean = df['Salary'].mean()
df['Salary'] = df['Salary'].fillna(salary_mean)
salary_mean
df

     Name  Age City     Salary
0   Komal   21   Pu  900000.00
1    Yash   20   Mu   20000.00
2    Maya   22   Na    3000.00
3   Megha   23   Ja   87350.00
4   Pooja   26   Pu  142743.75
5  Roshan   28   Na   30600.00
6   Tejas   30   Th   10000.00
7  Swaraj   53   Sa   19000.00
8  Sakshi   62   Be  142743.75
9   Madhu   70   Pa   72000.00

In [ ]:
df_